# Sync BRAIN MAKER GLB (and future large assets) to Azure Blob media container.
# Requires: az login (OIDC or interactive) + Contributor on rg-kinsho.
#
# Usage (PowerShell):
#   ./scripts/sync-media-to-blob.ps1
#   ./scripts/sync-media-to-blob.ps1 -SkipUpload   # only refresh media-config.js

param(
  [string]$ResourceGroup = 'rg-kinsho',
  [string]$DeploymentName = 'kinsho-resources',
  [switch]$SkipUpload
)

$ErrorActionPreference = 'Stop'

$account = az deployment group show `
  -g $ResourceGroup `
  -n $DeploymentName `
  --query 'properties.outputs.mediaStorageAccountName.value' -o tsv
$blobBase = az deployment group show `
  -g $ResourceGroup `
  -n $DeploymentName `
  --query 'properties.outputs.mediaBlobBaseUrl.value' -o tsv

if (-not $account -or -not $blobBase) {
  throw 'Media storage outputs not found. Deploy infra/resources.bicep first.'
}

$src = Join-Path $PSScriptRoot '..\web\public\assets\noumai-maker\head_allen_fit.glb'
$dest = 'noumai/head_allen_fit.glb'

if (-not $SkipUpload) {
  if (-not (Test-Path $src)) {
    throw "Missing GLB at $src — place the model locally once, then sync."
  }
  Write-Host "Uploading $src → $blobBase/$dest"
  az storage blob upload `
    --account-name $account `
    --auth-mode login `
    --container-name media `
    --name $dest `
    --file $src `
    --overwrite true `
    --content-type 'model/gltf-binary' | Out-Null
}

$configPath = Join-Path $PSScriptRoot '..\web\public\assets\noumai-maker\media-config.js'
@"
// Local override pointing at Azure Blob (generated by scripts/sync-media-to-blob.ps1)
window.KINSHO_MEDIA = {
  noumaiBrain: '$blobBase/noumai/head_allen_fit.glb',
};
"@ | Set-Content -Path $configPath -Encoding utf8

Write-Host "Updated $configPath"
Write-Host "Brain URL: $blobBase/noumai/head_allen_fit.glb"
